[package]
name = "ether"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
web3 = "0.16.0"
#ethkey = "0.3.1"
#ethrs = "0.9.0"


[[bin]]
name = "ether"
path = "main.rs"
